#!/bin/sh

# Set these paths appropriately

BIN=/home/melki/Documents/cours/tal/tme7/bin
CMD=/home/melki/Documents/cours/tal/tme7/cmd
LIB=/home/melki/Documents/cours/tal/tme7/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/french-abbreviations-utf8
PARFILE=${LIB}/french-utf8.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
