#!/bin/sh

# Set these paths appropriately

BIN=/home/melki/Documents/cours/tal/tme7/bin
CMD=/home/melki/Documents/cours/tal/tme7/cmd
LIB=/home/melki/Documents/cours/tal/tme7/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
