#!/bin/sh

# Set these paths appropriately

BIN=/home/melki/Documents/cours/tal/tme7/bin
CMD=/home/melki/Documents/cours/tal/tme7/cmd
LIB=/home/melki/Documents/cours/tal/tme7/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
