#!/bin/sh

# Set these paths appropriately

BIN=/home/melki/Documents/cours/tal/tme7/bin
CMD=/home/melki/Documents/cours/tal/tme7/cmd
LIB=/home/melki/Documents/cours/tal/tme7/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/tokenize.pl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/latin-abbreviations
PARFILE=${LIB}/latin.par
MWLFILE=${LIB}/latin-mwls

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE

