#!/bin/sh

# Set these paths appropriately

BIN=/home/melki/Documents/cours/tal/tme7/bin
CMD=/home/melki/Documents/cours/tal/tme7/cmd
LIB=/home/melki/Documents/cours/tal/tme7/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
